# Generated by Django 5.1.1 on 2024-10-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('voted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.individual')),
            ],
        ),
    ]
