# Generated by Django 5.1.1 on 2026-07-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_vote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=4, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('batch_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
