# Generated by Django 5.1.1 on 2024-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_voter_class_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_status',
            field=models.CharField(choices=[('Voted', 'Voted'), ('not_voted', 'not_voted')], default='not_voted', max_length=255),
        ),
    ]
