# Generated by Django 5.1.1 on 2024-10-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_voter_voter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_status',
            field=models.CharField(choices=[('Voted', 'Voted'), ('not_voted', 'not_voted'), ('pending', 'pending')], default='not_voted', max_length=255),
        ),
    ]
